### ISSUE TITLE
Build Error - bemtool boost

### ISSUE THREAD

**Issue by DBrusson** [FreeFem/FreeFem-sources#335]
Hi,  
I'm experiencing issues when attempting to compile FreeFem++. I tried with various compilers gcc11/gcc12 and Intel 2018/2021/2023 and openmpi 4.1/4.0

The OS : Red Hat Enterprise Linux release 8.7 (Ootpa)

Below is the result of reconfigure command, after downloading third parties and compiling petsc (without any apparent errors), and then the error I'm facing. Is there a way to circumvent that error or maybe use my own version of boost ?

Thank you for your help.

## Reconfigure

`./reconfigure `

```
INFO - PATH:
PATH=/usr/local/cmake/cmake-3.26.4/bin:/usr/local/openmpi/openmpi-4.1.6.gcc12/bin:/usr/local/gcc/gcc-12.2.0/bin:/usr/local/vim/vim-9.0/bin:/usr/local/bin/di:/home2020/home/di/brusson/HPC_tools/utilities:/usr/local/Modules/5.0.1/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/slurm/bin:/home2020/home/di/brusson/bin

INFO - config.param:
'--prefix=/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test'
'--enable-download'
'--enable-optim'
'--enable-m64'
'CC=/usr/local/gcc/gcc-12.2.0/bin/gcc'
'CXX=/usr/local/gcc/gcc-12.2.0/bin/g++'
'FC=/usr/local/gcc/gcc-12.2.0/bin/gfortran'
'F77=/usr/local/gcc/gcc-12.2.0/bin/gfortran'

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... /usr/local/gcc/gcc-12.2.0/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether /usr/local/gcc/gcc-12.2.0/bin/gcc accepts -g... yes
checking for /usr/local/gcc/gcc-12.2.0/bin/gcc option to enable C11 features... none needed
checking whether /usr/local/gcc/gcc-12.2.0/bin/gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of /usr/local/gcc/gcc-12.2.0/bin/gcc... gcc3
checking whether the compiler supports GNU C++... yes
checking whether /usr/local/gcc/gcc-12.2.0/bin/g++ accepts -g... yes
checking for /usr/local/gcc/gcc-12.2.0/bin/g++ option to enable C++11 features... (cached) unsupported
checking for /usr/local/gcc/gcc-12.2.0/bin/g++ option to enable C++98 features... none needed
checking dependency style of /usr/local/gcc/gcc-12.2.0/bin/g++... gcc3
checking for unzip... yes
checking for m4... yes
checking for bison... yes
checking for flex... yes
checking for cmake... yes
checking for patch... yes
checking whether the compiler supports GNU Fortran... yes
checking whether /usr/local/gcc/gcc-12.2.0/bin/gfortran accepts -g... yes
checking whether the compiler supports GNU Fortran 77... yes
checking whether /usr/local/gcc/gcc-12.2.0/bin/gfortran accepts -g... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to get verbose linking output from /usr/local/gcc/gcc-12.2.0/bin/gfortran... -v
checking for Fortran 77 libraries of /usr/local/gcc/gcc-12.2.0/bin/gfortran...  -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0 -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib/openmpi -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../.. -lgfortran -lm -lquadmath
checking  Size of fortran 77 integer ...            4
checking for dummy main to link with Fortran 77 libraries... none
checking for Fortran 77 name-mangling scheme... lower case, underscore, no extra underscore
configure:     ++ add f77 :  -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0 -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib/openmpi -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../.. -lgfortran -lm -lquadmath ;  -DAdd_   in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add fc :  -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0 -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib/openmpi -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../.. -lgfortran -lm -lquadmath ;  -DAdd_   in  plugin/seq/WHERE_LIBRARY-config "
checking for gcc... (cached) /usr/local/gcc/gcc-12.2.0/bin/gcc
checking whether the compiler supports GNU C... (cached) yes
checking whether /usr/local/gcc/gcc-12.2.0/bin/gcc accepts -g... (cached) yes
checking for /usr/local/gcc/gcc-12.2.0/bin/gcc option to enable C11 features... (cached) none needed
checking whether /usr/local/gcc/gcc-12.2.0/bin/gcc understands -c and -o together... (cached) yes
checking dependency style of /usr/local/gcc/gcc-12.2.0/bin/gcc... (cached) gcc3
checking for flex... flex
checking for lex output file root... lex.yy
checking for lex library... none needed
checking for library containing yywrap... no
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for deflate in -lz... yes
checking for pthread_create in -lpthread... yes
checking for omp_get_wtime in -liomp5... no
checking for clock_gettime in -lrt... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for sys/time.h... yes
checking for zlib.h... yes
configure:     ++ add pthread : -lpthread ;   in  plugin/seq/WHERE_LIBRARY-config "
checking wether we are on a MacIntosh... no
checking wether we are on  SunOS... no
checking wether we are on Microsoft Windows... no
checking prefix dir freefem++  ... /home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/lib/ff++/4.15
configure:     -----   CPU kind: x86_64 , intel/amd: yes 
checking whether the C compiler accepts -m64... yes
checking whether the C++ compiler accepts -m64... yes
checking whether the Fortran 77 compiler accepts -m64... yes
checking whether the C compiler accepts -fPIC... yes
checking whether the C++ compiler accepts -fPIC... yes
checking whether the Fortran 77 compiler accepts -fPIC... yes
checking whether to generate debugging information... no
checking whether the C compiler accepts -O3... yes
checking whether the C++ compiler accepts -O3... yes
checking whether the Fortran 77 compiler accepts -O3... yes
checking whether the C compiler accepts -mmmx... yes
checking whether the C++ compiler accepts -mmmx... yes
checking whether the Fortran 77 compiler accepts -mmmx... yes
checking whether the C compiler accepts -mavx2... yes
checking whether the C++ compiler accepts -mavx2... yes
checking whether the Fortran 77 compiler accepts -mavx2... yes
checking whether the C compiler accepts -mavx... yes
checking whether the C++ compiler accepts -mavx... yes
checking whether the Fortran 77 compiler accepts -mavx... yes
checking whether the C compiler accepts -msse4.2... yes
checking whether the C++ compiler accepts -msse4.2... yes
checking whether the Fortran 77 compiler accepts -msse4.2... yes
checking whether the C compiler accepts -msse2... yes
checking whether the C++ compiler accepts -msse2... yes
checking whether the Fortran 77 compiler accepts -msse2... yes
checking whether the C compiler accepts -msse... yes
checking whether the C++ compiler accepts -msse... yes
checking whether the Fortran 77 compiler accepts -msse... yes
configure:      CXXFLAGS =   -g  -m64 -fPIC -DNDEBUG -O3 -mmmx -mavx2 -mavx -msse4.2 -msse2 -msse  
checking whether the C++ compiler accepts -std=gnu++14... yes
configure:     ++ add cxx11 : -std=gnu++14 ;  -std=gnu++14 in  plugin/seq/WHERE_LIBRARY-config "
checking suffix to add to package name... none
checking for OpenGL/gl.h... no
checking for GL/gl.h... yes
checking for GLUT/glut.h... no
checking for GL/glut.h... yes
checking add suffix  ... yes
configure:  find real ( real )  petsc in /home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib/petsc/conf/petscvariables
configure:  choose MPI from petsc  : /usr/local/openmpi/openmpi-4.1.6.gcc12/bin/mpiexec 
checking for MPIRUN... /usr/local/openmpi/openmpi-4.1.6.gcc12/bin/mpiexec
checking for MPIRUN option: ... --oversubscribe
checking for mpipath ... 
yes
checking MPI_DOUBLE_COMPLEX... yes
configure:     ++ add mpifc : -pthread -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -Wl,-rpath -Wl,/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -Wl,--enable-new-dtags -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi  ;  -I/usr/local/openmpi/openmpi-4.1.6.gcc12/include  in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add mpif77 : -pthread -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -Wl,-rpath -Wl,/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -Wl,--enable-new-dtags -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi  ;  -I/usr/local/openmpi/openmpi-4.1.6.gcc12/include  in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add mpi : -pthread -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -Wl,-rpath -Wl,/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -Wl,--enable-new-dtags -lmpi  ;  -I/usr/local/openmpi/openmpi-4.1.6.gcc12/include  in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add petsc : -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib  -lpetsc  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -Wl,-rpath,/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -Wl,-rpath,/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0 -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0 -Wl,-rpath,/usr/local/gcc/gcc-12.2.0/lib64 -L/usr/local/gcc/gcc-12.2.0/lib64 -Wl,-rpath,/usr/local/openmpi/openmpi-4.1.6.gcc12/lib/openmpi -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib/openmpi -Wl,-rpath,/usr/local/gcc/gcc-12.2.0/lib -L/usr/local/gcc/gcc-12.2.0/lib -lHYPRE -lspqr -lumfpack -lklu -lcholmod -lamd -ldmumps -lmumps_common -lpord -lpthread -lscalapack -lsuperlu -lf2clapack -lf2cblas -lparmmg -lmmg -lmmg3d -lptesmumps -lptscotchparmetisv3 -lptscotch -lptscotcherr -lesmumps -lscotch -lscotcherr -lparmetis -lmetis -ltet -lm -ldl -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lm -lgfortran -lm -lgcc_s -lquadmath -lpthread -lstdc++ -lrt -lquadmath -ldl ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include/suitesparse in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add parmetis :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lparmetis ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add metis :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lmetis ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add ptscotch :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lptesmumps -lptscotchparmetisv3 -lptscotch -lptscotcherr -lesmumps -lscotch -lscotcherr ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add scotch : -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib     -lesmumps -lscotch -lscotcherr ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add mumps :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -ldmumps -lmumps_common -lpord -lpthread ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add tetgen :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -ltet ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add hpddm :   ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add superlu :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lsuperlu ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add mmg :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lmmg -lmmg3d ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add parmmg :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lparmmg ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add scalapack :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lscalapack ;    in  plugin/seq/WHERE_LIBRARY-config "
 **** add  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lmetis to ff_SUITESPARSE_LIB ******
configure:     ++ add suitesparse :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lspqr -lumfpack -lklu -lcholmod -lamd  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lmetis ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include/suitesparse -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add blaslapack :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lf2clapack -lf2cblas ;    in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add slepc : -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lslepc ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include/suitesparse in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add arpack : -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -larpack ;   in  plugin/seq/WHERE_LIBRARY-config "
configure:  with petsc  yes,  with slepc yes 
configure:  find complex (complex) petsc in /home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/c/lib/petsc/conf/petscvariables
configure:     ++ add petsccomplex : -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/c/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/c/lib  -lpetsc  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -Wl,-rpath,/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -Wl,-rpath,/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0 -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0 -Wl,-rpath,/usr/local/gcc/gcc-12.2.0/lib64 -L/usr/local/gcc/gcc-12.2.0/lib64 -Wl,-rpath,/usr/local/openmpi/openmpi-4.1.6.gcc12/lib/openmpi -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib/openmpi -Wl,-rpath,/usr/local/gcc/gcc-12.2.0/lib -L/usr/local/gcc/gcc-12.2.0/lib -lspqr -lumfpack -lklu -lcholmod -lamd -lzmumps -lmumps_common -lpord -lpthread -lscalapack -lsuperlu -lf2clapack -lf2cblas -lparmmg -lmmg -lmmg3d -lptesmumps -lptscotchparmetisv3 -lptscotch -lptscotcherr -lesmumps -lscotch -lscotcherr -lparmetis -lmetis -ltet -lm -ldl -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lm -lgfortran -lm -lgcc_s -lquadmath -lpthread -lstdc++ -lquadmath -ldl ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/c/include -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include/suitesparse -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add parmetis :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lparmetis  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add metis :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lmetis  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add ptscotch :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lptesmumps -lptscotchparmetisv3 -lptscotch -lptscotcherr -lesmumps -lscotch -lscotcherr  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add scotch : -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib     -lesmumps -lscotch -lscotcherr  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add mumps :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lzmumps -lmumps_common -lpord -lpthread  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add tetgen :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -ltet  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add hpddm :    -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/c/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add htool :   ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/c/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add superlu :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lsuperlu  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add mmg :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lmmg -lmmg3d  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add parmmg :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lparmmg  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add scalapack :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lscalapack   in  plugin/seq/WHERE_LIBRARY-config "
configure:     -- do not add suitesparse :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lspqr -lumfpack -lklu -lcholmod -lamd  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include/suitesparse -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add slepccomplex : -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/c/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/c/lib -lslepc ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/c/include -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include/suitesparse -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:  with petsc complex  yes, with slepc complex yes 
checking for wget... yes
checking for git... yes
checking for arit_zero in -lcadnafree... no
checking for /home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/3rdparty/cadna/cadnafree.h... no
configure:  without cadna ***** 
checking for fftw_execute in -lfftw3... yes
checking for fftw3.h... yes
configure:     ++ add fftw3 : -lfftw3 ;   in  plugin/seq/WHERE_LIBRARY-config "
 use BLAS/Lapack of petsc 
configure:     ++ add lapack :  ;    in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add blas : -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lf2clapack -lf2cblas ;    in  plugin/seq/WHERE_LIBRARY-config "
configure:  BLAS and LAPACK  from  petsc ***** 
checking for cblas.h... no
checking for Accelerate/cblas.h... no
checking for atlas/cblas.h... no
checking for cblas_zdotu_sub in -lcblas... no
configure:     -- do not add blas : -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lf2clapack -lf2cblas  in  plugin/seq/WHERE_LIBRARY-config "
checking for lapack in -lrt   -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0 -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib/openmpi -L/usr/local/gcc/gcc-12.2.0/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../.. -lgfortran -lm -lquadmath, -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lf2clapack -lf2cblas and -llapack ... yes
configure:     -- do not add lapack : -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lf2clapack -lf2cblas  in  plugin/seq/WHERE_LIBRARY-config "
amd/umfpack/suitesparse  of petsc
    lib:  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lspqr -lumfpack -lklu -lcholmod -lamd  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lmetis inc:  -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include/suitesparse -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include
configure:     ++ add amd :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lspqr -lumfpack -lklu -lcholmod -lamd  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lmetis ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include/suitesparse -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add umfpack :  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lspqr -lumfpack -lklu -lcholmod -lamd  -Wl,-rpath,/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -L/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/lib -lmetis ;   -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include/suitesparse -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include in  plugin/seq/WHERE_LIBRARY-config "
checking for times... yes
checking for sysconf... yes
checking for cstddef... yes
checking for stddef.h... yes
checking for semaphore.h... yes
checking for sys/mman.h... yes
checking for regex.h... yes
checking for unistd.h... (cached) yes
checking for malloc.h... yes
checking for asinh... yes
checking for acosh... yes
checking for atanh... yes
checking for getenv... yes
checking for jn... yes
checking for erfc... yes
checking for tgamma... yes
checking for gettimeofday... yes
checking for mallinfo... yes
checking for mstats... no
checking for srandomdev... no
checking for second_... no
checking for libtool... yes
checking for dlfcn.h... yes
checking for sin in -lm... yes
checking for dlinfo in -ldl... yes
checking whether dlopen links ok... yes
checking whether the C++ compiler accepts -rdynamic... yes
checking whether the C++ compiler accepts -fPIC... yes
checking whether the C compiler accepts -fPIC... yes
checking whether the C compiler accepts -fPIC... yes
checking whether the Fortran compiler accepts -fPIC... yes
checking whether the Fortran compiler accepts -fPIC... yes
checking whether the Fortran compiler accepts -fPIC... yes
checking whether the Fortran compiler accepts -fPIC... yes
checking whether the Fortran 77 compiler accepts -fallow-argument-mismatch... yes
checking whether the Fortran compiler accepts -fallow-argument-mismatch... yes
checking whether the Fortran 77 compiler accepts -fallow-invalid-boz... yes
checking whether the Fortran compiler accepts -fallow-invalid-boz... yes
checking for gsl-config... /usr/bin/gsl-config
checking for GSL - version >= 1.15... yes
configure:     ++ add gsl : -lgsl -lgslcblas -lm ;  -I/usr/include in  plugin/seq/WHERE_LIBRARY-config "
checking check mumps_seq... no
checking check libseq... no
checking check mumps_ptscotch... no
checking check mumps_scotch... no
checking check blacs... no
checking check freeyams... no
checking check mmg3d... no
checking check zlib... yes
checking check mshmet... no
checking check ipopt... no
checking check nlopt... no
checking kernel version... 4.18.0
checking libc version... libc-2.28
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for h5cc... /usr/bin/h5cc
checking for HDF5 type... serial
checking for HDF5 libraries... yes (version 1.10.5)
checking for hdf5.h... yes
checking for H5Fcreate in -lhdf5... yes
checking for H5PTcreate in -lhdf5_hl... yes
checking for matching HDF5 Fortran wrapper... /usr/bin/h5fc
checking for H5Cpp.h... yes
configure:     ++ add hdf5 :  -L/usr/lib64  -lhdf5_hl -lhdf5  -lsz -lz -ldl -lm ;  -I/usr/include in  plugin/seq/WHERE_LIBRARY-config "
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating 3rdparty/Makefile
config.status: creating 3rdparty/blas/Makefile
config.status: creating 3rdparty/arpack/Makefile
config.status: creating 3rdparty/umfpack/Makefile
config.status: creating 3rdparty/fftw/Makefile
config.status: creating src/Makefile
config.status: creating src/bamglib/Makefile
config.status: creating src/Graphics/Makefile
config.status: creating src/femlib/Makefile
config.status: creating src/Algo/Makefile
config.status: creating src/lglib/Makefile
config.status: creating src/ffgraphics/Makefile
config.status: creating src/ffgraphics/server/Makefile
config.status: creating src/ffgraphics/client/Makefile
config.status: creating src/fflib/Makefile
config.status: creating src/nw/Makefile
config.status: creating src/mpi/Makefile
config.status: creating src/bamg/Makefile
config.status: creating src/libMesh/Makefile
config.status: creating src/medit/Makefile
config.status: creating src/bin-win32/Makefile
config.status: creating plugin/Makefile
config.status: creating plugin/seq/Makefile
config.status: creating plugin/mpi/Makefile
config.status: creating examples/Makefile
config.status: creating examples/plugin/Makefile
config.status: creating examples/tutorial/Makefile
config.status: creating examples/misc/Makefile
config.status: creating examples/mpi/Makefile
config.status: creating examples/bem/Makefile
config.status: creating examples/hpddm/Makefile
config.status: creating examples/ffddm/Makefile
config.status: creating examples/eigen/Makefile
config.status: creating examples/examples/Makefile
config.status: creating examples/bug/Makefile
config.status: creating examples/3d/Makefile
config.status: creating examples/3dSurf/Makefile
config.status: creating examples/3dCurve/Makefile
config.status: creating config.h
config.status: executing depfiles commands
configure:   FreeFEM used download: yes 
configure:   --  Dynamic load facility: yes 
configure:   --  ARPACK (eigen value): yes 
configure:   --  UMFPACK (sparse solver): yes 
configure:   --  BLAS: yes 
configure:   --  with MPI:     yes
configure:     --  with PETSc: yes / PETSc complex: yes 
configure:     --  with SLEPc: yes / SLEPc complex: yes 
configure:     --  with hpddm: yes 
configure:     --  with htool: yes 
configure:     --  with bemtool: yes (need boost: yes and htool: yes) 
configure:   --  without libs:  
configure:   --  without plugins:  
configure:     progs: FreeFem++-nw bamg cvmsh2  FreeFem++-mpi ffmedit ffglut 
configure:       use of download freeyams  see 3rdparty/yams/freeyams.2011.02.22 (suface mesh adaptation)  
configure:       use of download mmg3d (v4)   see 3rdparty/mmg3d/mmg3d4/LICENCE.txt  
configure:       try to download: bemtool yams nlopt mumps_seq ipopt mshmet mmg3d 
configure:       use of download boost        see 3rdparty/boost/LICENSE_1_0.txt  
configure:       Please run "3rdparty/getall" to download all necessary packages before running make
```

## Compilation

`make -j2`

```
[...]
/usr/local/openmpi/openmpi-4.1.6.gcc12/bin/mpic++ -DHAVE_CONFIG_H -I. -I../..  -DPARALLELE -I./../fflib -I./../Graphics -I./../femlib -I./../bamglib/ -I/usr/local/openmpi/openmpi-4.1.6.gcc12/include  -I/usr/include -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include/suitesparse -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/r/include -I/home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/test/ff-petsc/c/include -DWITH_bemtool -DWITH_htool -I./../../3rdparty/include/BemTool/ -I./../../3rdparty/boost/include -I../../plugin/mpi  -DPARALLELE -DHAVE_ZLIB -g  -m64 -fPIC -DNDEBUG -O3 -mmmx -mavx2 -mavx -msse4.2 -msse2 -msse -std=gnu++14 -DBAMG_LONG_LONG  -DNCHECKPTR -fPIC -MT compositeFESpace.o -MD -MP -MF $depbase.Tpo -c -o compositeFESpace.o compositeFESpace.cpp &&\
mv -f $depbase.Tpo $depbase.Po
Dans le fichier inclus depuis ./../../3rdparty/boost/include/boost/math/tools/roots.hpp:25,
                 depuis ./../../3rdparty/boost/include/boost/math/special_functions/bessel.hpp:22,
                 depuis ./../../3rdparty/include/BemTool/bemtool/operator/../miscellaneous/specialfct.hpp:26,
                 depuis ./../../3rdparty/include/BemTool/bemtool/operator/operator.hpp:26,
                 depuis ./../../3rdparty/include/BemTool/bemtool/tools.hpp:41,
                 depuis compositeFESpace.cpp:15:
./../../3rdparty/boost/include/boost/math/special_functions/next.hpp: Dans la fonction « boost::math::tools::promote_args_t<RT1, RT2> boost::math::float_distance(const T&, const U&, const Policy&) »:
./../../3rdparty/boost/include/boost/math/special_functions/next.hpp:718:56: erreur: expected « ; » before « { » token
  718 |    BOOST_MATH_IF_CONSTEXPR (!std::is_same<T, U>::value)
      |                                                        ^
      |                                                        ;
  719 |    {
      |    ~                                                    
./../../3rdparty/boost/include/boost/math/special_functions/next.hpp:729:4: erreur: « else » sans « if » précédent
  729 |    else
      |    ^~~~
make[3]: *** [Makefile:708: compositeFESpace.o] Error 1
make[3]: *** Attente des tâches non terminées....
make[3] : on quitte le répertoire « /home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/src/mpi »
make[2]: *** [Makefile:552: all-recursive] Error 1
make[2] : on quitte le répertoire « /home2020/home/di/brusson/Imperium/FreeFem-sources-4.15/src »
make[1]: *** [Makefile:894: all-recursive] Error 1
make[1] : on quitte le répertoire « /home2020/home/di/brusson/Imperium/FreeFem-sources-4.15 »
make: *** [Makefile:762: all] Error 2
```

**Comment by prj-** [comment]
This is a boost error. We have little to no control over that. Could you maybe try an even newer GCC?

**Comment by DBrusson** [comment]
Unfortunately it doesn't work with gcc14. Is there a way to use my own boost instead of the 3rdparty one ?

**Comment by prj-** [comment]
Sure, the easiest way would be to simply copy/paste your boost includes files into `3rdparty/boost/include`.

**Comment by prj-** [comment]
Would you feel like making a contribution? This would require some adjustments to `configure.ac`. Also, could you please let us know which version of Boost you are using?

**Comment by DBrusson** [comment]
Unfortunately I'm lacking time and knowledge of configure to contribute, but here is what I used:

- gcc 14.2.0
- openmpi 4.1.8
- boost 1.87.0 (compiled with the above gcc and openmpi)

And here is a snippet of the script I used:

```
cd FreeFem-sources-4.15
./configure --prefix=${rootdir} --enable-download --enable-optim --enable-m64
./3rdparty/getall -a
pushd 3rdparty/ff-petsc
make -j24 petsc-slepc
popd
mkdir 3rdparty/boost
cp -r ${BOOSTROOT}/include 3rdparty/boost/
touch 3rdparty/boost/done.tag # Otherwise it will download bemtool-boost and overwrite it

./reconfigure

make -j24
make -j24 install
```

**Comment by prj-** [comment]
So likely a bug was fixed in between 1.86.0 and 1.87.0. @phtournier, could you please upload a new tarball?

**Comment by DBrusson** [comment]
Unfortunately the error is still here with the new boost in develop branch. Maybe it works with my own version of boost because of the way I install boost ?

```
echo "using mpi ;" >> user-config.jam
pushd tools/build/
./bootstrap.sh
./b2 install --prefix=${rootdir}
export PATH=${rootdir}/bin:${PATH}
popd
b2 -j28 --layout=tagged --user-config=user-config.jam variant=release threading=single,multi link=static,shared stage --stagedir=${rootdir}
b2 install --user-config=user-config.jam --prefix=${rootdir}
mv libs ${rootdir}
```

**Comment by prj-** [comment]
Could you please send the latest log (with the error) you have? We don't build Boost.

**Comment by prj-** [comment]
You are using the `develop` branch, right?

**Comment by DBrusson** [comment]
Yep:

```
git checkout
Votre branche est à jour avec 'origin/develop'.
```

But now that you mention you don't build boost, that behavior isn't that surprising I guess. Our cluster may have a specificity that requires a custom boost build (I install my own boost version because that's how it was done before, I never questioned that...)

**Comment by prj-** [comment]
Could you please share the result of `/usr/local/openmpi/openmpi-4.1.6.gcc12/bin/mpic++ -show`?

**Comment by DBrusson** [comment]
```
/usr/local/openmpi/openmpi-4.1.6.gcc12/bin/mpic++ -show
/usr/local/gcc/gcc-12.2.0/bin/g++ -I/usr/local/openmpi/openmpi-4.1.6.gcc12/include -pthread -L/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -Wl,-rpath -Wl,/usr/local/openmpi/openmpi-4.1.6.gcc12/lib -Wl,--enable-new-dtags -lmpi
```

**Comment by DBrusson** [comment]
Oh sorry, I was indeed using g++-14, I made a mistake when pasting the snippet of error log in my previous message. The attached log file is correct though.

Here is the correct snippet:
```
[...]
/usr/local/openmpi/4.1.8.gcc14.2.0/bin/mpic++ -DHAVE_CONFIG_H -I. -I../..  -DPARALLELE -I./../fflib -I./../Graphics -I./../femlib -I./../bamglib/ -I/usr/local/openmpi/4.1.8.gcc14.2.0/include  -I/usr/include -I/home2020/home/di/brusson/FreeFem-sources/test/ff-petsc/r/include/suitesparse -I/home2020/home/di/brusson/FreeFem-sources/test/ff-petsc/r/include -I/home2020/home/di/brusson/FreeFem-sources/test/ff-petsc/c/include -DWITH_bemtool -DWITH_htool -I./../../3rdparty/include/BemTool/ -I./../../3rdparty/boost/include -I../../plugin/mpi  -DPARALLELE -DHAVE_ZLIB -g  -m64 -fPIC -DNDEBUG -O3 -mmmx -mavx2 -mavx -msse4.2 -msse2 -msse -std=gnu++14 -DBAMG_LONG_LONG  -DNCHECKPTR -fPIC -MT compositeFESpace.o -MD -MP -MF $depbase.Tpo -c -o compositeFESpace.o compositeFESpace.cpp &&\
mv -f $depbase.Tpo $depbase.Po
config.status: creating ff-mpirun
chmod a+x ff-mpirun
Dans le fichier inclus depuis ./../../3rdparty/boost/include/boost/math/tools/roots.hpp:25,
                 depuis ./../../3rdparty/boost/include/boost/math/special_functions/bessel.hpp:22,
                 depuis ./../../3rdparty/include/BemTool/bemtool/operator/../miscellaneous/specialfct.hpp:26,
                 depuis ./../../3rdparty/include/BemTool/bemtool/operator/operator.hpp:26,
                 depuis ./../../3rdparty/include/BemTool/bemtool/tools.hpp:41,
                 depuis compositeFESpace.cpp:15:
./../../3rdparty/boost/include/boost/math/special_functions/next.hpp: Dans la fonction « boost::math::tools::promote_args_t<RT1, RT2> boost::math::float_distance(const T&, const U&, const Policy&) »:
./../../3rdparty/boost/include/boost/math/special_functions/next.hpp:718:56: erreur: expected « ; » before « { » token
  718 |    BOOST_MATH_IF_CONSTEXPR (!std::is_same<T, U>::value)
      |                                                        ^
      |                                                        ;
  719 |    {
      |    ~                                                    
./../../3rdparty/boost/include/boost/math/special_functions/next.hpp:729:4: erreur: « else » sans « if » précédent
  729 |    else
      |    ^~~~
make[3]: *** [Makefile:708: compositeFESpace.o] Error 1
make[3]: *** Attente des tâches non terminées....
make[3] : on quitte le répertoire « /home2020/home/di/brusson/FreeFem-sources/src/mpi »
make[2]: *** [Makefile:552: all-recursive] Error 1
make[2] : on quitte le répertoire « /home2020/home/di/brusson/FreeFem-sources/src »
make[1]: *** [Makefile:894: all-recursive] Error 1
make[1] : on quitte le répertoire « /home2020/home/di/brusson/FreeFem-sources »
make: *** [Makefile:762: all] Error 2
```

Sorry again for that mistake
